/// Flutter icons SortSliderIcon
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SortSliderIcon
///      fonts:
///       - asset: fonts/SortSliderIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SortSliderIcon {
  SortSliderIcon._();

  static const _kFontFam = 'SortSliderIcon';

  static const IconData settings_sliders = IconData(
    0xe800,
    fontFamily: _kFontFam,
  );
}
